name: Deploy Yolo

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEV_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.DEV_INSTANCE_SSH_KEY }}
          script: |
            cd ~/PolyAIFursa
            git fetch origin
            git checkout -B dev origin/dev

            # --- yolo ---
            cd ~/PolyAIFursa/services/yolo
            .venv/bin/pip install -r requirements.txt
            sudo systemctl restart yolo.service

            # --- agent ---
            cd ~/PolyAIFursa/services/agent
            .venv/bin/pip install -r requirements.txt
            sudo systemctl restart agent.service

            # --- frontend ---
            cd ~/PolyAIFursa/services/frontend
            npm install
            NEXT_PUBLIC_AGENT_URL=http://${{ secrets.DEV_INSTANCE_IP }}:8000 npm run build
            sudo systemctl restart frontend.service


            

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod instance
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.PROD_INSTANCE_SSH_KEY }}
          script: |
            cd ~/PolyAIFursa
            git fetch origin
            git checkout -B main origin/main

            # --- yolo ---
            cd ~/PolyAIFursa/services/yolo
            .venv/bin/pip install -r requirements.txt
            sudo systemctl restart yolo.service

            # --- agent ---
            cd ~/PolyAIFursa/services/agent
            .venv/bin/pip install -r requirements.txt
            sudo systemctl restart agent.service

            # --- frontend ---
            cd ~/PolyAIFursa/services/frontend
            npm install
            NEXT_PUBLIC_AGENT_URL=http://${{ secrets.PROD_INSTANCE_IP }}:8000 npm run build
            sudo systemctl restart frontend.service